config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :appointments
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :equipment

  def user_name=(name)
    self.user = User.find_or_create_by(name: name)
  end

  def user_name
    self.user ? self.user.name : nil
  end

  def equipment_name=(name)
    self.equipment = Equipment.find_or_create_by(name: name)
  end

  def equipment_name
    self.equipment ? self.equipment.name : nil
  end

end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :appointments
  has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments
  has_many :equipment, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @appointments = Appointment.all
  end

  def show
    @appointment = Appointment.find(params[:id])
    @appointment_new = Appointment.new
  end

  def new
    @appointment = Appointment.new
  end

  def create
    user = User.find_or_create_by(name: appointment_params[:user_name])

    @appointment = user.appointments.build(appointment_params)

    if @appointment.save
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])

    @appointment.update(appointment_params)

    if @appointment.save
      redirect_to @appointment
    else
      render :edit
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    user = @appointment.user
    @appointment.destroy
    flash[:notice] = "Appointment deleted."
    redirect_to user_path(user)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:user_name, :equipment_id, :date, :time)
  end

end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    @user.update(user_params)

    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted."
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/edit.html.erb
<h1>Edit a Gym Appointment at Globo Gym</h1>

<%= form_for @appointment  do |f| %>
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <br />
  <br />
  <%= f.collection_select :equipment_id, Equipment.all, :id, :name %>
  <br />
  <br />
  <%= f.label :date %>
  <%= f.text_field :date %>
  <br />
  <br />
  <%= f.label :time %>
  <%= f.text_field :time %>
  <br />
  <br />
  <%= f.submit "Update Appointment"%>
<% end %>

app/views/appointments/index.html.erb
<h1>Appointment Index</h1>

<% @appointments.each do |appointment| %>
  <%= link_to "#{appointment.date}, #{appointment.time}", appointment_path(appointment) %>
  <br/>
  <br/>
<% end %>

app/views/appointments/new.html.erb
<h1>Create a Gym Appointment at Globo Gym</h1>

<%= form_for @appointment  do |f| %>
  <%= f.label :user_name %>
  <%= f.text_field :user_name, list: "users_autocomplete" %>
  <datalist id="users_autocomplete">
    <% User.all.each do |user| %>
      <option value="<%= user.name %>">
    <% end %>
  </datalist>
  <br />
  <br />
  <%= f.label :equipment_to_use %>
  <%= f.collection_select :equipment_id, Equipment.all, :id, :name %>
  <br />
  <br />
  <%= f.label :date %>
  <%= f.text_field :date %>
  <br />
  <br />
  <%= f.label :time %>
  <%= f.text_field :time %>
  <br />
  <br />
  <%= f.submit "Create Appointment"%>
<% end %>

app/views/appointments/show.html.erb
<h1>Appointment Page</h1>

<b>User: </b><%= link_to @appointment.user.name, user_path(@appointment.user) %>
<br/>
<br/>
<b>Day: </b><%= @appointment.date %>
<br/>
<br/>
<b>Time: </b><%= @appointment.time %>
<br/>
<br/>
<b>Equipment: </b><%= @appointment.equipment.name %>
<br/>
<br/>
<b>Equipment Info: </b><%= @appointment.equipment.use %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMiniSoloProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <br />
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <br />
  <br />
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<h1>User Index</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user_path(user) %> | <%= user.appointments.count %> appointments
  <br/>
  <br/>
<% end %>

app/views/users/new.html.erb
<h1>Create a User</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <br />
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <br />
  <br />
  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name.split[0] %>'s User Page</h1>

<b>User Name: </b><%= @user.name %>
<br/>
<br/>
<b>Bio: </b><%= @user.bio %>
<br/>
<br/>
<b>Current Appointments:</b>
<br/>
<% count = 1 %>
<% @user.appointments.each do |appointment| %>
  <%= link_to "Appointment # #{count}", appointment_path(appointment) %><br/>
  Date: <%= appointment.date %><br/>
  Time: <%= appointment.time %><br/>
  Equipment: <%= appointment.equipment.name %><br/>
  <%= form_for appointment, url: edit_appointment_path(appointment), method: :get do |f| %>
    <%= f.submit "Edit" %>
  <% end %>
  <%= form_for appointment, method: :delete do |f| %>
    <%= f.submit "Delete" %>
  <% end %>
  <br/>
  <% count += 1 %>
<% end %>
<%= button_to "New Appointment", new_appointment_path, method: :get %>